# Generated by Django 5.1.7 on 2025-03-31 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'managed': True, 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
    ]
