# Generated by Django 5.1.7 on 2025-03-31 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'managed': True, 'verbose_name': 'Actor', 'verbose_name_plural': 'Actors'},
        ),
    ]
